# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-02 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='pw_hash',
            field=models.CharField(default=None, max_length=60),
            preserve_default=False,
        ),
    ]
